USE PlanningManagerDev
GO

CREATE TABLE TaskStates
(
ID Int IDENTITY NOT NULL
PRIMARY KEY,
Name VarChar(50) NOT NULL,
InsertedBy Int NULL
FOREIGN KEY REFERENCES Users(ID)
)
GO

CREATE TABLE TaskLabels
(
ID Int IDENTITY NOT NULL
PRIMARY KEY,
Name VarChar(50) NOT NULL,
Color VarChar(10) NULL,
InsertedBy Int NULL
FOREIGN KEY REFERENCES Users(ID)
)
GO

CREATE TABLE TaskGroups
(
ID Int IDENTITY NOT NULL
PRIMARY KEY,
Name VarChar(50) NOT NULL,
Color VarChar(10) NULL,
InsertedBy Int NULL
FOREIGN KEY REFERENCES Users(ID)
)
CREATE

GO TABLE TaskPriorities
(
ID Int IDENTITY NOT NULL
PRIMARY KEY,
Name TinyInt NOT NULL
)
GO

CREATE Table Tasks
(
ID Int IDENTITY NOT NULL
PRIMARY KEY,
Name VarChar(50) NOT NULL,
Description NVarChar NULL,
Priority Int NOT NULL
FOREIGN KEY REFERENCES TaskPriorities(ID),
Label Int NOT NULL
FOREIGN KEY REFERENCES TaskLabels(ID),
[Group] Int NOT NULL
FOREIGN KEY REFERENCES TaskGroups(ID),
[State] Int NOT NULL
FOREIGN KEY REFERENCES TaskStates(ID),
StartDate DateTime2 NULL,
EndDate DateTime2 NULL,
InsertedBy Int NULL
FOREIGN KEY REFERENCES Users(ID),
InsertedAt DateTime2 NOT NULL
)
GO

CREATE TABLE TaskUserMaps
(
ID Int IDENTITY NOT NULL
PRIMARY KEY,
TaskID Int NOT NULL
FOREIGN KEY REFERENCES Tasks(ID),
UserID Int NOT NULL
FOREIGN KEY REFERENCES Users(ID)
)
GO