//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlanningManagmentDataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class C__RefactorLog
    {
        public System.Guid OperationKey { get; set; }
    }
}
